### ISSUE TITLE
Can not display next sunny day on Firefox

### ISSUE THREAD

**Issue by gtonye** [gtonye/next-sunny-day#3]
## Environment

Firefox 48.0.1 - Mac OS 10.11.1 (15B42)

## Description

* Actions: Go to nextsunnyday.gtonye.com > Enter a city > Click on find out
* Expected: next sunny day page
* Results: infinite loading overlay

### console output
```
JSON.parse: unexpected character at line 5 column 1 of the JSON dataapp.cb298eaa0eaeefd2f6fb.js:1:7659

EXCEPTION: JSON.parse: unexpected character at line 5 column 1 of the JSON datavendor.cb298eaa0eaeefd2f6fb.js:21:870

uncaught exception: JSON.parse: unexpected character at line 5 column 1 of the JSON data
```

**Comment by gtonye** [comment]
Fixed in v1.1.2
